<a href="https://colab.research.google.com/github/Darianath/ML/blob/main/%D0%9B%D0%A01_%D0%9D%D0%B0%D0%B7%D0%B0%D1%80%D0%BE%D0%B2%D0%B0_4_8_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

## Підготовка

In [1]:
import numpy as np
np.__version__

'2.1.3'

## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [2]:
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
c= a+b
d= a-b
e= a*4
v=b*(-2)
n = a*b
print(c)
print(d)
print(e)
print(v)
print(n)

[10  4  4 13]
[ 4 -8  6  5]
[28 -8 20 36]
[ -6 -12   2  -8]
[ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.


In [4]:
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])

d1=np.dot(u, v)
d2= u @ v
norm_u=np.linalg.norm(u)
norm_v=np.linalg.norm(v)
c_a= d1/(norm_u * norm_v)


print(d1)
print(d2)
print(norm_v)
print(norm_u)
print(c_a)

31
31
6.48074069840786
7.0
0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [9]:
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])

print(A+B)
print(A-B)
print(A*B)
print(A*5)
print(A.T)

[[4 3 5]
 [9 3 6]]
[[ 2  7 -7]
 [-5 -3  2]]
[[  3 -10  -6]
 [ 14   0   8]]
[[15 25 -5]
 [10  0 20]]
[[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [14]:
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

a= A@B
print(a)
print(a.shape)

m = A[0, 0] * B[0, 1] + A[0, 1] * B[1, 1]+ A[0, 2] * B[2, 1]
print(m)
print(a[0,1])

[[17  7]
 [32  5]]
(2, 2)
7
7


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [15]:
v = np.array([12, 7, 19, 4, 11, 8])

r2=np.roll(v, 2)
l3=np.roll(v, -3)
r= np.roll(r2,-2)

print(r2)
print(l3)
print(r)

[11  8 12  7 19  4]
[ 4 11  8 12  7 19]
[12  7 19  4 11  8]


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [23]:
v = np.array([42, 17, 29, 8, 35, 23])

a=np.sort(v)
d=a[::-1]
i=np.argsort(v)[::-1]

print(f"{a}\n{d}\n{i}\n{v[i]}")

[ 8 17 23 29 35 42]
[42 35 29 23 17  8]
[0 4 2 5 1 3]
[42 35 29 23 17  8]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [25]:
v = np.array([-12, -4, 3, 18, 27, 35, 48])

c=np.clip(v, -5, 30)
t=np.where(v !=c)[0]

print(f"{c}\n{t}")

[-5 -4  3 18 27 30 30]
[0 5 6]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [24]:
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
l, c= np.unique(v,return_counts=True)
m=l[np.argmax(c)]

print(f"{l}\n{a}\n{m}")

[2 4 7 9]
[ 8 17 23 29 35 42]
7


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [27]:
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

a=np.rot90(A, -1)
b=np.rot90(A, 2)
c=np.rot90(A, 1)

print(f"{a}\n{b}\n{c}")

[[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]
[[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]
[[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [28]:
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

b1= np.pad(A, 1, mode="constant", constant_values=-1)
b2=np.pad(A, 2, mode="constant", constant_values=0)

print(f"{b1}\n{b1.shape}\n{b2}\n{b2.shape}")

[[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
(5, 5)
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
(7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [33]:
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

p= A[row_order][:,col_order]
r=p[np.argsort(row_order)][:, np.argsort(col_order)]

print(f"{p}\n{r}\n{np.array_equal(A, r)}")

[[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
True


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [34]:
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

u=np.triu(A)
l=np.tril(A)
su=np.triu(A, 1)
sl=np.tril(A, -1)
r=l+su
print(f"{u}\n{l}\n{su}\n{sl}\n{r}")

[[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]
[[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]
[[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]
[[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]
[[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [43]:
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

o=np.outer(a,b)
print(f"{o}\n{o.shape}\n{o[2, 1], a[2]*b[1]}")

[[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]
(4, 3)
(np.int64(35), np.int64(35))


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [44]:
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])

AB=np.kron(A, B)
BA=np.kron(B, A)

print(f"{AB}\n{BA}\n{AB.shape, BA.shape}\n{np.array_equal(AB,BA)}")

[[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]
[[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]
((4, 4), (4, 4))
False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [45]:
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])

A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])

c1 = A1 @ B1 - B1 @ A1
c2 = A2 @ B2 - B2 @ A2
print(f"{c1}\n{np.allclose(c1,0)}\n{c2}\n{np.allclose(c2,0)}")

[[0 0]
 [0 0]]
True
[[ 0 -6]
 [-3  0]]
False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [47]:
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])

q= x @ A @ x

X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

q_all=np.einsum("ij, jk, ik->i", X, A, X)

print(f"{q}\n{q_all}")


35
[35 17 27]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [49]:
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

A2=np.linalg.matrix_power(A, 2)
A3=np.linalg.matrix_power(A,3)

print(f"{A2}\n{A3}\n{np.array_equal(A3, A2 @ A)}")

[[1 2 1]
 [1 1 2]
 [2 1 1]]
[[2 3 3]
 [3 2 3]
 [3 3 2]]
True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [50]:
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

rA=np.linalg.matrix_rank(A)
rB=np.linalg.matrix_rank(B)

print(f"{rA}\n{rB}\n{rA == min(A.shape)}\n{rB == min(B.shape)}")

3
2
True
False


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [51]:
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

val, vec=np.linalg.eigh(A)

l=A @ vec
r= vec* val
print(f"{val}\n{vec}\n{np.allclose(l,r)}")

[2. 7.]
[[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]
True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [52]:
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

X=np.column_stack((np.ones_like(x),x))
c, r,rank, s = np.linalg.lstsq(X, y, rcond=None)

a,b= c
y_pred = X @ c
sse=np.sum((y- y_pred)**2)

print(f"{a}\n{b}\n{y_pred}\n{sse}")

2.019999999999998
2.0100000000000002
[ 2.02  4.03  6.04  8.05 10.06]
0.13099999999999973
